# Generated by Django 2.0.2 on 2020-10-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.jpeg', upload_to='profilepic/'),
        ),
    ]
