# Generated by Django 2.0.2 on 2020-10-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_auto_20201031_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
