# Generated by Django 2.0.2 on 2020-11-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0009_auto_20201101_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdepartment',
            name='contacts',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='policeauthorities',
            name='contacts',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
