# Generated by Django 2.0.2 on 2020-11-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0010_auto_20201101_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoliceAuthorities',
            new_name='PoliceAuthority',
        ),
    ]
