# Generated by Django 2.0.2 on 2020-11-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0011_auto_20201101_1944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthDepartment',
            new_name='Authority',
        ),
        migrations.RenameModel(
            old_name='PoliceAuthority',
            new_name='Hospital',
        ),
    ]
