# Generated by Django 2.0.2 on 2020-11-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0013_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='news',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
