# Generated by Django 2.0.2 on 2020-11-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0014_auto_20201101_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='post_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
