# Generated by Django 2.0.2 on 2020-11-02 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0015_alert_post_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='news',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='name',
            new_name='title',
        ),
    ]
