# Generated by Django 2.0.2 on 2020-11-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0018_auto_20201102_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
    ]
