# Generated by Django 2.0.2 on 2020-11-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0019_remove_alert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='contacts',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
